import type { Project } from "@/types/portfolio";

export const PROJECTS: Project[] = [
	{
		title: "KriegerDataForge",
		summary: "A multi-tenant data platform spanning 18 repositories, built and operated solo. An OAuth 2.0 and OIDC identity provider issuing RS256 JWTs with a JWKS endpoint for cross-app SSO, a shared Python SDK every tenant backend installs instead of reimplementing auth, a Terraform control plane declaring every environment, and a centralized CI/CD library inherited by every repo.",
		subtitle: "Multi-Tenant Platform Ecosystem",
		category: "personal",
		status: "in-development",
		description: "A multi-tenant data platform I design, build, and operate on my own, spread across 18 repositories. At its center is an OAuth 2.0 and OIDC identity provider that issues RS256 JWTs and publishes a JWKS endpoint, so every product on the platform shares one account and one sign in. Around that sit a shared Python SDK that tenant backends install instead of reimplementing auth, a Terraform control plane that declares every environment, and a centralized CI/CD library where deploy behavior, security gates, and version discipline are defined once and inherited everywhere. Two first party products are being built on it today, a boutique e-commerce storefront and a free nutrition tracker.",
		highlights: [
			"One identity provider and one shared user table give true SSO across every app on the platform",
			"Three isolated environments, sandbox, dev, and prod, sharing no keys, databases, or service keys",
			"Every deploy is a manual dispatch behind an environment approval gate and a fail closed authorization gate",
			"Tenant backends carry no auth code at all, they verify the hub's JWKS through the shared SDK",
		],
		techStack: [
			"Next.js",
			"React",
			"TypeScript",
			"TailwindCSS",
			"FastAPI",
			"Python",
			"SQLModel",
			"PostgreSQL",
			"Alembic",
			"OAuth 2.0 / OIDC",
			"Terraform",
			"GitHub Actions",
			"Docker",
			"Vercel",
			"GCP",
		],
		architecture: [
			{
				label: "Frontend",
				color: "cosmic",
				items: ["Next.js", "React", "TypeScript", "TailwindCSS"],
			},
			{
				label: "Backend",
				color: "green",
				items: ["FastAPI", "Python", "SQLModel", "PostgreSQL"],
			},
			{
				label: "Platform",
				color: "stellar",
				items: ["Terraform", "GitHub Actions", "Docker", "Vercel"],
			},
		],
		links: {
			github: "https://github.com/Needless2Say",
			youtube: [
				"https://www.youtube.com/embed/emxHI2ybPJ4?si=MjbDHFItsyvVzN-y",
				"https://www.youtube.com/embed/j3F10BulHSs?si=Dq08f0ymaPxngzs5",
			],
		},
		featured: true,
	},
	{
		title: "Metadata Reconciliation System",
		subtitle: "Data Platform Engineering",
		category: "professional",
		status: "live",
		description: "This started with an email. In mid April the data governance team reported losing three to four hours of metadata work that they would have to redo by hand. Schema deploys recreate warehouse objects and silently strip the descriptions, tags, and ownership contacts attached to them, and the existing fix was fragile snapshot and reapply logic inside every deployment. I replaced it with declarative reconciliation. Version controlled desired state became the single write path, continuously converged by engines running inside the warehouse itself on their own schedule, with no CI runner or external orchestrator anywhere in the production path. Architected and implemented end to end, mid April to end of August 2026, from the first conversation to working end to end in production.",
		highlights: [
			"Recovery went from three to four hours of manual rework to seconds. 20+ schema deployments absorbed since go-live, every one restored with no human involvement",
			"Thousands of metadata rows under management, governing any warehouse object type across both proprietary and fully custom metadata categories",
			"Multi-tenant with self-service onboarding. A team creates a repo from the template I built and is a live consumer in minutes",
			"The governance team authors from a spreadsheet through an issue template instead of writing YAML, removing the engineering dependency entirely",
			"Every phase is idempotent, time boxed, and fully resumable, with state in a control table so a mid-run crash costs nothing",
			"Change detection runs on content hashes rather than timestamps, and repair flips state with one set based update instead of per-object work",
			"Eight independent fail closed checks make the failure mode inaction, never corruption, and a golden hash parity test pins both execution paths to byte-identical results",
			"Onboarding a new metadata category is configuration with zero engine code, and every phase exits immediately when there is no work, so idle days cost almost nothing",
		],
		techStack: [
			"Snowflake",
			"Python",
			"SQL",
			"YAML",
			"Git",
			"GitHub Actions",
			"GCP",
			"Pydantic",
			"CI/CD",
		],
		links: {},
		featured: true,
		diagram: "metadata-reconciliation",
	},
	{
		title: "KDF Identity Provider",
		subtitle: "Auth Service · KriegerDataForge",
		category: "personal",
		status: "security-review",
		description: "The identity service every app on the platform delegates to, plus the hosted login and consent UI that sits in front of it. It implements the authorization code flow with PKCE, rotating refresh tokens, per client audience isolation, argon2id password hashing, account lockout, signing key rotation, and a login audit log. The UI is a backend for frontend that holds the service key server side, so the identity service itself is never reachable from a browser and a cloned login page cannot authenticate anyone.",
		highlights: [
			"Authorization code flow with PKCE, rotating refresh tokens, per client audience isolation",
			"Consumers verify tokens locally against the JWKS with no per request round trip",
			"Under adversarial security review ahead of its first DEV deployment",
		],
		techStack: [
			"FastAPI",
			"Python",
			"OAuth 2.0 / OIDC",
			"JWT",
			"argon2id",
			"PostgreSQL",
			"Next.js",
			"TypeScript",
		],
		links: {},
	},
	{
		title: "Tiffany's Space",
		summary: "A production boutique e-commerce storefront. Server authoritative on every price, total, and inventory count, with a two step reserve then pay checkout that is transactional, idempotent, and concurrency safe, plus an admin dashboard for catalog and order management.",
		subtitle: "E-commerce Platform · KriegerDataForge",
		category: "personal",
		status: "pre-launch",
		description: "A production boutique storefront where my sister will sell curated clothing, books, handmade crafts, art, and accessories. Customers browse and search the catalog, keep a persistent cart, and move through a two step reserve then pay checkout with order history. A dedicated admin dashboard lets her manage products and orders directly. The server stays authoritative on every price, total, and inventory count, and the checkout is transactional, idempotent, and concurrency safe. Stripe is wired and deliberately inert until it is switched on at launch.",
		highlights: [
			"Server recomputes every price and total, nothing money related is trusted from the client",
			"Two step reserve then pay checkout that is idempotent and safe under concurrent orders",
			"Admin dashboard for catalog and order management, plus data subject request handling",
		],
		techStack: [
			"Next.js",
			"React",
			"TypeScript",
			"TailwindCSS",
			"FastAPI",
			"PostgreSQL",
			"SQLModel",
			"Stripe",
			"Zod",
		],
		links: {},
	},
	{
		title: "Calorie Tracker",
		summary: "A free forever nutrition tracker on a 41 field food database, with custom foods and meals, a guided creation wizard, and all nutrition totals recomputed server side so client submitted values are never trusted.",
		subtitle: "Nutrition App · KriegerDataForge",
		category: "personal",
		status: "in-development",
		description: "A free forever food and nutrition tracker built for casual users and beginners, the people who bounce off MyFitnessPal's paywall or find Cronometer too dense. Log meals, track calories and macros against personal goals, and review trends over time, on top of a 41 field food database with a guided food and meal creation wizard and a daily tracker that saves as you type. Core tracking stays free permanently, with revenue coming from non-intrusive ads and partnerships rather than a paywall. This was the first app built on the platform and the one I return to once the identity layer and the storefront are finished.",
		highlights: [
			"41 field food database with custom foods, custom meals, and a guided creation wizard",
			"Nutrition totals recomputed server side so client submitted numbers are never trusted",
			"Roadmap climbs from AI meal insights to community features and an AI personal trainer",
		],
		techStack: [
			"Next.js",
			"React",
			"TypeScript",
			"FastAPI",
			"Python",
			"PostgreSQL",
			"SQLModel",
		],
		links: {
			youtube: ["https://www.youtube.com/embed/j3F10BulHSs?si=Dq08f0ymaPxngzs5"],
		},
	},
	{
		title: "kdf-sdk",
		subtitle: "Python Platform Library · KriegerDataForge",
		category: "personal",
		status: "in-development",
		description: "The shared Python library every tenant backend installs, so building on the platform is one dependency line rather than a rewrite. Its core job is stateless RS256 token verification against the identity provider's JWKS with no database round trip. On top of that it ships a FastAPI application factory, auth dependencies, ownership checks, pagination, rate limiting, observability, SQLModel database infrastructure, blob storage, email, and log injection sanitization. It runs inside every app on the platform, so a weakness here would ship everywhere at once, which is why it carries the heaviest test suite in the ecosystem.",
		highlights: [
			"Stateless JWT verification against the hub JWKS, no database round trip per request",
			"Batteries included FastAPI foundation so no tenant repo reimplements platform plumbing",
		],
		techStack: [
			"Python",
			"FastAPI",
			"SQLModel",
			"JWT",
			"pytest",
			"Ruff",
			"mypy",
		],
		links: {},
	},
	{
		title: "kdf-fmt",
		subtitle: "Python Formatter & Linter · KriegerDataForge",
		category: "personal",
		status: "in-development",
		description: "A Python formatter and linter I wrote from scratch with zero runtime dependencies, built directly on the standard library's ast and tokenize modules. It enforces the parts of my house style that off the shelf tools do not cover, including sectioned module preambles, aligned assignment runs, Google docstring contracts, and 120 column canonical wrapping. Rules run in three tiers, auto fixed, blocking, and advisory, and every rule is remappable per project through TOML. It is the style gate across the platform's Python repos and works on any Python codebase.",
		highlights: [
			"Stdlib only at runtime, no third party dependencies to audit or pin",
			"Frozen written spec is the contract, with golden fixtures freezing the rendering",
		],
		techStack: [
			"Python",
			"ast",
			"tokenize",
			"pytest",
		],
		links: {},
	},
	{
		title: "Video Game Database",
		subtitle: "Web Application · KriegerDataForge",
		category: "personal",
		status: "planned",
		description: "A searchable game catalog queued up as a future tenant app, browsing and filtering titles by genre, platform, and rating. Like every other app on the platform it will own no identity of its own, delegating sign in to the KDF identity provider and standing up its own service behind the shared SDK.",
		techStack: [
			"Next.js",
			"React",
			"FastAPI",
			"PostgreSQL",
		],
		links: {},
	},
];
