import type { Project } from "@/types/portfolio";

export const PROJECTS: Project[] = [
	{
		title: "KriegerDataForge",
		summary: "A multi-tenant data platform spanning 18 repositories, built and operated solo. An OAuth 2.0 and OIDC identity provider issuing RS256 JWTs with a JWKS endpoint for cross-app SSO, a shared Python SDK every tenant backend installs instead of reimplementing auth, a Terraform control plane declaring every environment, and a centralized CI/CD library inherited by every repo.",
		subtitle: "Multi-Tenant Platform Ecosystem",
		category: "personal",
		status: "in-development",
		description: "A multi-tenant data platform I design, build, and operate on my own, spread across 18 repositories. At its center is an OAuth 2.0 and OIDC identity provider that issues RS256 JWTs and publishes a JWKS endpoint, so every product on the platform shares one account and one sign in. Around that sit a shared Python SDK that tenant backends install instead of reimplementing auth, a Terraform control plane that declares every environment, and a centralized CI/CD library where deploy behavior, security gates, and version discipline are defined once and inherited everywhere. Two first party products are being built on it today, a boutique e-commerce storefront and a free nutrition tracker.",
		highlights: [
			"One identity provider and one shared user table give true SSO across every app on the platform",
			"Three isolated environments, sandbox, dev, and prod, sharing no keys, databases, or service keys",
			"Every deploy is a manual dispatch behind an environment approval gate and a fail closed authorization gate",
			"Tenant backends carry no auth code at all, they verify the hub's JWKS through the shared SDK",
		],
		techStack: [
			"Next.js",
			"React",
			"TypeScript",
			"TailwindCSS",
			"FastAPI",
			"Python",
			"SQLModel",
			"PostgreSQL",
			"Alembic",
			"OAuth 2.0 / OIDC",
			"Terraform",
			"GitHub Actions",
			"Docker",
			"Vercel",
			"GCP",
		],
		architecture: [
			{
				label: "Frontend",
				color: "cosmic",
				items: ["Next.js", "React", "TypeScript", "TailwindCSS"],
			},
			{
				label: "Backend",
				color: "green",
				items: ["FastAPI", "Python", "SQLModel", "PostgreSQL"],
			},
			{
				label: "Platform",
				color: "stellar",
				items: ["Terraform", "GitHub Actions", "Docker", "Vercel"],
			},
		],
		links: {
			github: "https://github.com/Needless2Say",
			youtube: [
				"https://www.youtube.com/embed/emxHI2ybPJ4?si=MjbDHFItsyvVzN-y",
				"https://www.youtube.com/embed/j3F10BulHSs?si=Dq08f0ymaPxngzs5",
			],
		},
		featured: true,
	},
	{
		title: "Metadata Reconciliation System",
		subtitle: "Data Platform Engineering",
		category: "professional",
		status: "live",
		description: "I found this problem months before I solved it properly. Schema deployments were silently stripping the descriptions, tags, and ownership contacts attached to warehouse objects, because recreating an object discards everything attached to it. My first fix captured that metadata ahead of each deployment and reapplied it afterward, covering every level metadata can attach to and ten or more object types, and I wired it into the deployment pipeline across all five environments. It held the line, but it was fragile and it lived inside every deployment. Then in mid April the data governance team reported losing three to four hours of metadata work they would have to redo by hand, and I replaced the approach entirely with declarative reconciliation. Governance metadata is now declared once in version control and restored automatically whenever a deployment removes it, with nobody watching and nothing to redo. Architected and implemented end to end, mid April to end of August 2026, from the first conversation to working end to end in production.",
		highlights: [
			"Recovery went from three to four hours of manual rework to seconds. 20+ schema deployments absorbed since go-live, every one restored with no human involvement",
			"Thousands of metadata rows under management, spanning every warehouse object type and both standard and fully custom metadata, with headroom to scale by orders of magnitude",
			"Multi-tenant from the start. Any team can onboard itself and manage its own metadata independently, with no engineering work from me",
			"The governance team works entirely from the tool they already use, with no YAML to write and no engineering dependency to wait on",
			"Designed to be safe to re-run. The failure mode is inaction rather than corruption, so recovery is always a replay and a bad day costs nothing",
			"Runs unattended every day and costs almost nothing on days when there is no work to do",
		],
		techStack: [
			"Snowflake",
			"Python",
			"SQL",
			"YAML",
			"Git",
			"GitHub Actions",
			"GCP",
			"Pydantic",
			"CI/CD",
		],
		links: {},
		featured: true,
	},
	{
		title: "Streamlit Dashboard Platform",
		subtitle: "Platform Engineering",
		category: "professional",
		status: "live",
		description: "Two business critical dashboards landed on me after the original developers left, with no handover. I read through both codebases, took ownership, and rebuilt the observability dashboard from a flat structure into a feature based architecture with a shared core. Then I turned that architecture into a template repository any tenant team can start from, sitting on a stack of shared Python packages underneath it for authentication, cloud access, Snowflake access, and the shared Streamlit layer. A team that wants a dashboard now writes only the dashboard. Everything else, down to the cloud infrastructure and the deployment pipeline, is already set up for them.",
		highlights: [
			"Inherited two business critical dashboard repositories with no knowledge transfer, read through 300+ files across both, and became the owner and single escalation path for the teams that depend on them",
			"Rebuilt the observability dashboard from a flat layout into a feature based architecture with a shared core, retired the legacy codebase entirely, and wrote the developer standards and documentation behind it so anyone on the team can contribute",
			"Turned that architecture into a template repository any tenant team can start from. A new dashboard begins with SSO, cloud access, Snowflake access, and the shared UI layer already wired in, and ships empty feature folders so it stays lean",
			"Built the shared Python package layer underneath it, creating the PKCE single sign on package and the Streamlit utilities package from scratch and contributing the cloud and Snowflake connectivity into two existing shared packages. Improvements to any of them reach every dashboard through a version bump, with no change in the consuming app",
			"Automated the provisioning so a tenant team never touches infrastructure. Repository setup, per environment secrets and variables, CI/CD, and the GCP infrastructure and deployment target are all handled for them",
			"Serves 100+ daily users across every data domain on the platform, with Streamlit cross session caching layered on so repeat views do not re-query Snowflake",
		],
		techStack: [
			"Python",
			"Streamlit",
			"Snowflake",
			"SQL",
			"GCP",
			"Docker",
			"GitHub Actions",
			"OAuth 2.0 / PKCE",
			"Pydantic",
		],
		links: {},
		featured: true,
	},
	{
		title: "Governed Exception Workflows",
		subtitle: "Product Engineering",
		category: "professional",
		status: "live",
		description: "The data governance team's quality scores were full of noise. Rules they already knew were not meaningful, test rules, rules that always warn or always fail. I built the workflow that lets them retire that noise deliberately, as governed records carrying a validity window and a stated reason, so suppressing a rule is an auditable decision rather than a silent deletion.",
		highlights: [
			"Built a governed exception workflow for data quality rules, then extended the same pattern to a second domain, which proved it as a reusable platform pattern rather than a one off feature",
			"Every exception is a governed record with a validity window, a stated reason, and full audit fields. Scores recalculate to exclude suppressed rules, and a toggle reveals the true unfiltered state underneath",
			"In real use. Users have collectively retired double digit numbers of non actionable rules, and a partner team bulk loaded tens of thousands of already known exceptions at launch",
		],
		techStack: ["Python", "Streamlit", "Snowflake", "SQL"],
		links: {},
	},
	{
		title: "Data Pipeline Engineering",
		subtitle: "Data Engineering",
		category: "professional",
		status: "live",
		description: "Pipeline and query work across the platform's warehouse layer, from the validation framework underneath a custom pipeline builder to the queries behind the dashboards and the alerting that tells teams when their data is late or wrong.",
		highlights: [
			"Introduced Pydantic into the architecture of a custom pipeline builder library, championed it through design review with my tech lead, and replaced hundreds of lines of hand written validation with a model hierarchy that rejects bad configuration before a pipeline ever runs",
			"Found that pipeline failure notifications had been silently missing every data source onboarded after a legacy lookup table went stale, so teams could be unaware their data was broken. Rebuilt the notification queries and proved the fix added the missing sources without dropping any",
			"Rewrote 33 queries and 6 dependent views to cover every data domain on the platform, and built three reusable query templates that turned onboarding a new domain from multi day development into instantiation",
			"Roughly halved execution time on the hot query paths, cut data scanned from about 50MB to 28MB, and eliminated disk spill",
		],
		techStack: ["Python", "Snowflake", "SQL", "Airflow", "Pydantic"],
		links: {},
	},
	{
		title: "KDF Identity Provider",
		subtitle: "Auth Service · KriegerDataForge",
		category: "personal",
		status: "security-review",
		description: "The identity service every app on the platform delegates to, plus the hosted login and consent UI that sits in front of it. It implements the authorization code flow with PKCE, rotating refresh tokens, per client audience isolation, argon2id password hashing, account lockout, signing key rotation, and a login audit log. The UI is a backend for frontend that holds the service key server side, so the identity service itself is never reachable from a browser and a cloned login page cannot authenticate anyone.",
		highlights: [
			"Authorization code flow with PKCE, rotating refresh tokens, per client audience isolation",
			"Consumers verify tokens locally against the JWKS with no per request round trip",
			"Under adversarial security review ahead of its first DEV deployment",
		],
		techStack: [
			"FastAPI",
			"Python",
			"OAuth 2.0 / OIDC",
			"JWT",
			"argon2id",
			"PostgreSQL",
			"Next.js",
			"TypeScript",
		],
		links: {},
	},
	{
		title: "Tiffany's Space",
		summary: "A production boutique e-commerce storefront. Server authoritative on every price, total, and inventory count, with a two step reserve then pay checkout that is transactional, idempotent, and concurrency safe, plus an admin dashboard for catalog and order management.",
		subtitle: "E-commerce Platform · KriegerDataForge",
		category: "personal",
		status: "pre-launch",
		description: "A production boutique storefront where my sister will sell curated clothing, books, handmade crafts, art, and accessories. Customers browse and search the catalog, keep a persistent cart, and move through a two step reserve then pay checkout with order history. A dedicated admin dashboard lets her manage products and orders directly. The server stays authoritative on every price, total, and inventory count, and the checkout is transactional, idempotent, and concurrency safe. Stripe is wired and deliberately inert until it is switched on at launch.",
		highlights: [
			"Server recomputes every price and total, nothing money related is trusted from the client",
			"Two step reserve then pay checkout that is idempotent and safe under concurrent orders",
			"Admin dashboard for catalog and order management, plus data subject request handling",
		],
		techStack: [
			"Next.js",
			"React",
			"TypeScript",
			"TailwindCSS",
			"FastAPI",
			"PostgreSQL",
			"SQLModel",
			"Stripe",
			"Zod",
		],
		links: {},
	},
	{
		title: "Calorie Tracker",
		summary: "A free forever nutrition tracker on a 41 field food database, with custom foods and meals, a guided creation wizard, and all nutrition totals recomputed server side so client submitted values are never trusted.",
		subtitle: "Nutrition App · KriegerDataForge",
		category: "personal",
		status: "in-development",
		description: "A free forever food and nutrition tracker built for casual users and beginners, the people who bounce off MyFitnessPal's paywall or find Cronometer too dense. Log meals, track calories and macros against personal goals, and review trends over time, on top of a 41 field food database with a guided food and meal creation wizard and a daily tracker that saves as you type. Core tracking stays free permanently, with revenue coming from non-intrusive ads and partnerships rather than a paywall. This was the first app built on the platform and the one I return to once the identity layer and the storefront are finished.",
		highlights: [
			"41 field food database with custom foods, custom meals, and a guided creation wizard",
			"Nutrition totals recomputed server side so client submitted numbers are never trusted",
			"Roadmap climbs from AI meal insights to community features and an AI personal trainer",
		],
		techStack: [
			"Next.js",
			"React",
			"TypeScript",
			"FastAPI",
			"Python",
			"PostgreSQL",
			"SQLModel",
		],
		links: {
			youtube: ["https://www.youtube.com/embed/j3F10BulHSs?si=Dq08f0ymaPxngzs5"],
		},
	},
	{
		title: "kdf-sdk",
		subtitle: "Python Platform Library · KriegerDataForge",
		category: "personal",
		status: "in-development",
		description: "The shared Python library every tenant backend installs, so building on the platform is one dependency line rather than a rewrite. Its core job is stateless RS256 token verification against the identity provider's JWKS with no database round trip. On top of that it ships a FastAPI application factory, auth dependencies, ownership checks, pagination, rate limiting, observability, SQLModel database infrastructure, blob storage, email, and log injection sanitization. It runs inside every app on the platform, so a weakness here would ship everywhere at once, which is why it carries the heaviest test suite in the ecosystem.",
		highlights: [
			"Stateless JWT verification against the hub JWKS, no database round trip per request",
			"Batteries included FastAPI foundation so no tenant repo reimplements platform plumbing",
		],
		techStack: [
			"Python",
			"FastAPI",
			"SQLModel",
			"JWT",
			"pytest",
			"Ruff",
			"mypy",
		],
		links: {},
	},
	{
		title: "kdf-fmt",
		subtitle: "Python Formatter & Linter · KriegerDataForge",
		category: "personal",
		status: "in-development",
		description: "A Python formatter and linter I wrote from scratch with zero runtime dependencies, built directly on the standard library's ast and tokenize modules. It enforces the parts of my house style that off the shelf tools do not cover, including sectioned module preambles, aligned assignment runs, Google docstring contracts, and 120 column canonical wrapping. Rules run in three tiers, auto fixed, blocking, and advisory, and every rule is remappable per project through TOML. It is the style gate across the platform's Python repos and works on any Python codebase.",
		highlights: [
			"Stdlib only at runtime, no third party dependencies to audit or pin",
			"Frozen written spec is the contract, with golden fixtures freezing the rendering",
		],
		techStack: [
			"Python",
			"ast",
			"tokenize",
			"pytest",
		],
		links: {},
	},
	{
		title: "Video Game Database",
		subtitle: "Web Application · KriegerDataForge",
		category: "personal",
		status: "planned",
		description: "A searchable game catalog queued up as a future tenant app, browsing and filtering titles by genre, platform, and rating. Like every other app on the platform it will own no identity of its own, delegating sign in to the KDF identity provider and standing up its own service behind the shared SDK.",
		techStack: [
			"Next.js",
			"React",
			"FastAPI",
			"PostgreSQL",
		],
		links: {},
	},
];
